baseURL = "https://oscarigrexas.github.io/blog/"
languageCode = "es-es"
title = "Sota de todos los palos"
theme = "archie"
# copyright = "© Athul"
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[pagination]
pagerSize = 3

[params]
mode = "toggle"
useCDN = false
subtitle = "La tecnología, y la vida más allá de la tecnología."
mathjax = true
katex = true
customcss = ["css/custom.css", "css/custom_fonts.css"]
logo = true
favicon = "favicon.ico"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/oscarigrexas"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/oscarigrexas"

# Main menu Items

[[menu.main]]
name = "Inicio"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Etiquetas"
url = "/tags"
weight = 3

[[menu.main]]
name = "Sobre mí"
url = "/about"
weight = 4
